name: "CT and Spectre-SCT related checks"
on:
  pull_request:
  push:

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        parameter_set: ["44", "65", "87"]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build the Jasmin compiler
      run: |
        git clone --branch main --depth 1 https://gitlab.com/jasmin-lang/jasmin-compiler.git
        cd jasmin-compiler/compiler
        nix-shell --run 'make'
    - name: Check whether the code is constant-time.
      run: env JASMINCT='jasmin-compiler/compiler/jasmin-ct' PARAMETER_SET=${{ matrix.parameter_set }} make check-ct
    - name: Check whether the code is speculative constant-time.
      run: env JASMINCT='jasmin-compiler/compiler/jasmin-ct' PARAMETER_SET=${{ matrix.parameter_set }} make check-sct
