name: "Known answer tests"
on:
  pull_request:
  push:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v3
    - run: nix-shell --run 'echo Installed dependencies.'
    - run: nix-shell --run 'make test'
    - run: nix-shell --run 'make large-kat-test'
    - run: nix-shell --run 'make check-ct'
