name: "Known answer tests"
on:
  pull_request:
  push:

jobs:
  kat-tests:
    name: kat-tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        parameter_set: ["44", "65", "87"]
        implementation_type: ["ref", "avx2"]
        exclude: # TODO: Implement.
          - parameter_set: "87"
            implementation_type: "avx2"
    steps:
    - uses: actions/checkout@master
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build the Jasmin compiler
      run: |
        git clone --branch main --depth 1 https://gitlab.com/jasmin-lang/jasmin-compiler.git
        cd jasmin-compiler/compiler
        nix-shell --run 'make'
    - name: Install pytest and pycryptodome
      run: python3 -m pip install pytest pycryptodome
    - name: Run known-answer tests
      run: env JASMINC='jasmin-compiler/compiler/jasminc' PARAMETER_SET=${{ matrix.parameter_set }} IMPLEMENTATION_TYPE=${{ matrix.implementation_type }} make test
