name: "Known answer tests (arm-m4)"
on:
  pull_request:
  push:

jobs:
  arm-m4-kat-tests:
    if: github.ref == 'refs/heads/main'
    name: kat-tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        parameter_set: ["44", "65", "87"]
        implementation_type: ["ref", "lowram"]
    steps:
    - uses: actions/checkout@master
    - name: Get nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Install qemu-arm and arm-none-linux-gnueabihf-gcc
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static gcc-arm-linux-gnueabihf
    - name: Build the Jasmin compiler
      run: |
        git clone --branch main --depth 1 https://gitlab.com/jasmin-lang/jasmin-compiler.git
        cd jasmin-compiler/compiler
        nix-shell --run 'make'
    - name: Install pytest and pycryptodome
      run: python3 -m pip install pytest pycryptodome
    - name: Run known-answer tests
      run: env QEMU_LD_PREFIX=/usr/arm-linux-gnueabihf make JASMINC='jasmin-compiler/compiler/jasminc' CROSS_COMPILER='arm-linux-gnueabihf-gcc' ARCHITECTURE='arm-m4' PARAMETER_SET=${{ matrix.parameter_set }} IMPLEMENTATION_TYPE=${{ matrix.implementation_type }} test
