name: "Ensure the code can be protected against Spectre-RSB attacks."
on:
  pull_request:
  push:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        parameter_set: ["44", "65", "87"]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell rsb-checker.nix --run 'echo Installed dependencies.'
    - run: nix-shell rsb-checker.nix --run 'env PARAMETER_SET=${{ matrix.parameter_set }} make check-rsb'
